### ISSUE TITLE
middle names

### ISSUE THREAD

**Issue by scarver2** [berkmancenter/namae#10]
```ruby
namae = Namae.parse( 'Homer Jay Simpson')
=> family="Simpson", given="Homer Jay"
````
Is it possible to tell Namae that the second name is a middle name instead of a given name? I understand that technically, it is a given name. Just looking for a way to parse the middle name in one pass.

In the meantime, this code works by making the assumption that a person has only one first name.
```ruby
first_name, middle_name = namae.given.split(' ', 2) if namae.given
```

**Comment by inukshuk** [comment]
I think this is pretty much impossible, because there may be different interpretations as to what is and isn't a middle name. If you know that, in your context, second given name always is a middle name you could adjust the grammar accordingly, but I guess using the second pass is easier to do.

**Comment by scarver2** [comment]
Thanks for the info @inukshuk
 
My solution was to split on the first space encountered and force any secondary names to be the middle name. This handles most English names correctly with few edge cases.

```ruby
first_name, middle_name = namae.given.split(' ', 2) if namae.given
```
