### ISSUE TITLE
Fails to detect name parts with asterisk in name

### ISSUE THREAD

**Issue by scarver2** [berkmancenter/namae#13]
`namae = Namae.parse('Gump *, Bubba')` returns empty array instead of `[#<Name family="Gump *" given="Bubba">]`

**Comment by aaronchi** [comment]
Doesn't work with numerics either. Would be nice if special chars/numbers were treated the same as UCASE words to ensure that the parser doesn't die on unusual data.

**Comment by inukshuk** [comment]
If we do that it's very hard to tell, after the fact, whether or not the parser recognized a name -- this seems to be very much like swallowing errors: it may seem convenient, but an error is an error, and usually it's easier to deal with it where it occurs.
