### ISSUE TITLE
The Honorable title

### ISSUE THREAD

**Issue by danchenkov** [berkmancenter/namae#17]
The Honorable and some other titles are not handled correctly. Is there a way to override racc rules?

```
Namae.parse('The Honorable Chelsea Block')
=> [#<Name family="Block" given="The Honorable Chelsea">]
```

**Comment by inukshuk** [comment]
It should be sufficient to adjust the lexer patterns. Take a look at `Namae::Parser.instance.options` -- specifically the `:title` regex.
