### ISSUE TITLE
Prefixed and Compound Word Surnames

### ISSUE THREAD

**Issue by PatrickTulskie** [berkmancenter/namae#3]
Namae doesn't seem to work correctly with prefixed and compound word family names.  For example:

    >> Namae::Name.parse("Justin Du Bois")
     => #<Name family="Bois" given="Justin Du"> 

More about prefixed and compound family names here: http://www.barbarahenritze.com/index.php/genealogical-research/genealogy-articles/32-prefixes-suffixes-hyphenates-compound-words-and-titles

I'll try to come up with a fix at some point but I figured I'd open up an issue to get the ball rolling.

**Comment by PatrickTulskie** [comment]
Oh awesome.  This is in the latest version of the gem?

**Comment by inukshuk** [comment]
No sorry, the examples above should all work, but like I said compound surnames only really work in 'sort order' (i.e., with a comma).
