### ISSUE TITLE
What is dropping particle

### ISSUE THREAD

**Issue by Bennet-Sunder** [berkmancenter/namae#34]
I can see in the `members` that `dropping_particle` is one of the things that can be parsed. I'm unable to find what it means. Could you please give me sample names which has this so that I can handle this case as well.

**Comment by inukshuk** [comment]
A dropping particle is something like the "van" in "Ludwig van Beethoven" (dropping,  because the name would be sorted under 'B') as opposed to a non dropping particle "van"  as in  "Vincent van  Gogh" (typically sorted under 'V').

**Comment by Bennet-Sunder** [comment]
But "van" in both the names is being parsed into `particle` and not into `dropping_particle` for "Ludwig van Beethoven" like you have explained. Example here https://repl.it/repls/OblongHopefulWeb

**Comment by inukshuk** [comment]
Well, yes the parser cannot distinguish between the two syntactically. We just have this in the name object API to make it possible create names using the distinction (which is important, e.g., if you export the names for use with a CSL processor).

**Comment by Bennet-Sunder** [comment]
Thanks for you quick help.
