### ISSUE TITLE
v 1.1.0 can't parse the name correctly, as it was in previous versions

### ISSUE THREAD

**Issue by IgorKhlebnikoff** [berkmancenter/namae#41]
::Namae.parse("Tom Van de Weghe")
 => []
::Namae.parse("Tom Van De Weghe")
 => []
::Namae.parse("tom van de weghe")
 =>` [#<Name family="weghe" particle="tom van de">]`

**Comment by inukshuk** [comment]
Thanks!

@lostmahbles it's probably best to simplify handling of particles. See my commit above and let me know if this looks good to you. Basically, I'm completely ignoring dropping particles for the time being (there's more effort necessary to support them properly) and the `include_particle_in_family` option applies to all particles now.

**Comment by inukshuk** [comment]
@IgorKhlebnikoff should be fixed in 1.1.1.
