### ISSUE TITLE
Lists of names with variable separators

### ISSUE THREAD

**Issue by dshorthouse** [berkmancenter/namae#8]
Is it outside the scope of namae to parse lists of names? For example, I have variably structured lists of names such as

* John D. Smith; Jack R. Johnson; Emily Tanner
* Smith, John D.; Johnson, Jack R.; Tanner, Emily
* John D. Smith, Jack R. Johnson & Emily Tanner
* C. Foster; C. Hamel, C. Desroches

**Comment by inukshuk** [comment]
I think this is definitely something the parser should support. Actually, it already work *almost* if you adjust the separator pattern `Namae.options[:separator]`.

For example:

    > Namae.options[:separator] = /\s*(\band\b|\&|;)\s*/i
    > Namae.parse 'John D. Smith; Jack R. Johnson; Emily Tanner'
    => [#<Name family="Tanner" given="John D. Smith; Jack R. Johnson; Emily">]

    # Does not work because we tokenize the words based on whitespace only

     > Namae.parse 'John D. Smith ; Jack R. Johnson ; Emily Tanner'
     => [#<Name family="Smith" given="John D.">, #<Name family="Johnson" given="Jack R.">, #<Name family="Tanner" given="Emily">]
     # With a space before the semicolon it works

     > Namae.parse 'C. Foster ; C. Hamel, C. Desroches'
     => [#<Name family="Foster" given="C.">, #<Name family="C. Hamel" given="C. Desroches">]

     # Does not work by default, but if we do....
     > Namae.options[:prefer_comma_as_separator] = true
     > Namae.parse 'C. Foster ; C. Hamel, C. Desroches'
     => [#<Name family="Foster" given="C.">, #<Name family="Hamel" given="C.">, #<Name family="Desroches" given="C.">]

So if I see this correctly we just need to make sure that something that matches `separator` is not consumed as part of a word.

**Comment by dshorthouse** [comment]
Thanks for this. The requirement for a whitespace before the semicolon is a bit of a problem for me. So, I may have to use a custom, regex-based .split prior to sending each candidate name to Namae.parse

**Comment by inukshuk** [comment]
This should be supported now. Using 0.10.0 you won't have to adjust the patterns, but you still need to set the prefer-comma option if you have lists that contain a comma both between names as well as between parts of names. Semicolons are not consumed as part of the name anymore either.
